/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.pangramia.services.exceptions;


/**
 * Common Error Codes
 */
public enum PBErrorCode implements org.apache.thrift.TEnum {
  /**
   * No information available about the error
   */
  UNKNOWN(1),
  /**
   * The format of the request data was incorrect
   */
  BAD_DATA_FORMAT(2),
  /**
   * Not permitted to perform action
   */
  PERMISSION_DENIED(3),
  /**
   * Unexpected problem with the service
   */
  INTERNAL_ERROR(4),
  /**
   * A required parameter/field was absent
   */
  DATA_REQUIRED(5),
  /**
   * Operation denied due to data model limit
   */
  LIMIT_REACHED(6),
  /**
   * Operation denied due to user storage limit
   */
  QUOTA_REACHED(7),
  /**
   * Username and/or password incorrect
   */
  INVALID_AUTH(8),
  /**
   * Authentication token expired
   */
  AUTH_EXPIRED(9),
  /**
   * Change denied due to data model conflict
   */
  DATA_CONFLICT(10),
  /**
   * Content of submitted note was malformed
   */
  VALIDATION(11),
  /**
   * Service shard with account data is temporarily down
   */
  SHARD_UNAVAILABLE(12),
  /**
   * Operation denied due to data model limit, where something such
   * as a string length was too short
   */
  LEN_TOO_SHORT(13),
  /**
   * Operation denied due to data model limit, where something such
   * as a string length was too long
   */
  LEN_TOO_LONG(14),
  /**
   * Operation denied due to data model limit, where there were
   * too few of something.
   */
  TOO_FEW(15),
  /**
   * Operation denied due to data model limit, where there were
   * too many of something.
   */
  TOO_MANY(16),
  /**
   * Operation denied because it is currently unsupported.
   */
  UNSUPPORTED_OPERATION(17),
  /**
   * Operation denied because access to the corresponding object is
   * prohibited in response to a take-down notice.
   */
  TAKEN_DOWN(18),
  /**
   * Operation denied because the calling application has reached
   * its hourly API call limit for this user.
   */
  RATE_LIMIT_REACHED(19),
  /**
   * The given resource is not found
   */
  NOT_FOUND(20);

  private final int value;

  private PBErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PBErrorCode findByValue(int value) { 
    switch (value) {
      case 1:
        return UNKNOWN;
      case 2:
        return BAD_DATA_FORMAT;
      case 3:
        return PERMISSION_DENIED;
      case 4:
        return INTERNAL_ERROR;
      case 5:
        return DATA_REQUIRED;
      case 6:
        return LIMIT_REACHED;
      case 7:
        return QUOTA_REACHED;
      case 8:
        return INVALID_AUTH;
      case 9:
        return AUTH_EXPIRED;
      case 10:
        return DATA_CONFLICT;
      case 11:
        return VALIDATION;
      case 12:
        return SHARD_UNAVAILABLE;
      case 13:
        return LEN_TOO_SHORT;
      case 14:
        return LEN_TOO_LONG;
      case 15:
        return TOO_FEW;
      case 16:
        return TOO_MANY;
      case 17:
        return UNSUPPORTED_OPERATION;
      case 18:
        return TAKEN_DOWN;
      case 19:
        return RATE_LIMIT_REACHED;
      case 20:
        return NOT_FOUND;
      default:
        return null;
    }
  }
}
