spring:
  application:
    name: stream-microservice
  data:
    cassandra:
      keyspace-name: eventsvr
      contact-points: localhost
      port: 9042

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
  instance:
      leaseRenewalIntervalInSeconds: 10
      leaseExpirationDurationInSeconds: 30

server:
  port: 5555
